spring.application.name=ch25
server.port=8085

spring.thymeleaf.cache=false
spring.devtools.restart.enabled=false

# MongoDB properties
spring.mongodb.uri=mongodb+srv://agh1055:${MONGODB_PASSWORD}@cluster0.hwd3z4e.mongodb.net/tacoclouddb
